AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: AWS Serverless Spring Boot 2 API - com.kischuk.springboot::kischuk-springboot
Globals:
  Api:
    EndpointConfiguration: REGIONAL

Resources:
  KischukSpringbootFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: com.kischuk.springboot.StreamLambdaHandler::handleRequest
      Runtime: java8
      CodeUri: target/kischuk-springboot-1.0-SNAPSHOT-lambda-package.zip
      MemorySize: 512
      Policies: AWSLambdaBasicExecutionRole
      Timeout: 30
      Events:
        GetResource:
          Type: Api
          Properties:
            Path: /{proxy+}
            Method: any

Outputs:
  KischukSpringbootApi:
    Description: URL for application
    Value: !Sub 'https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod/ping'
    Export:
      Name: KischukSpringbootApi
